name: axa_automation
on: 
  push:
    branches:
      [ main ]
jobs:
  playwrighttest:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.41.2-focal
      env:
        ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
    steps:
      - name: Run Tests
        run: |
          echo "Start Testing AT"
          echo "Install dependencies from lockfile"
          npm ci --silent
          echo "Run playwrite tests"
          npm run test:ci --verbose  # Add --verbose flag to see more details
