name: axa_automation
on: 
  push:
    branches:
      [ main ]
jobs:
  playwrighttest:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.42.2-focal
      env:
        ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci --silent --verbose
      - name: Run Tests
        run: |
          echo "Start Testing AT"
          echo "Install dependencies from lockfile"
          echo "Run playwrite tests"
          npm run test:ci --verbose  # Add --verbose flag to see more details
